"""Add check-in fields to ticket

Revision ID: 76b65716a84e
Revises: bbdc3163eab7
Create Date: 2025-04-07 06:12:55.453214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b65716a84e'
down_revision = 'bbdc3163eab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('is_checked_in')

    # ### end Alembic commands ###
