"""Add Ticket model and venue/time_frame fields to Event model

Revision ID: ca9799af61ff
Revises: e60791f543ef
Create Date: 2025-02-12 01:32:10.004211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9799af61ff'
down_revision = 'e60791f543ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('time_frame', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time_frame')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
