"""Add Ticket model and venue/time_frame fields to Event model

Revision ID: cb691430e7e1
Revises: ca9799af61ff
Create Date: 2025-02-12 04:26:42.311936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb691430e7e1'
down_revision = 'ca9799af61ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('bulk_min_tickets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bulk_discount_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('free_ticket_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('free_tickets', sa.Integer(), nullable=True))
        batch_op.drop_column('time_frame')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_frame', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('free_tickets')
        batch_op.drop_column('free_ticket_min')
        batch_op.drop_column('bulk_discount_percent')
        batch_op.drop_column('bulk_min_tickets')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
