"""Initial migration

Revision ID: f06e74b282fd
Revises: 
Create Date: 2025-04-09 16:38:57.397390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06e74b282fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('bulk_min_tickets', sa.Integer(), nullable=True),
    sa.Column('bulk_discount_percent', sa.Float(), nullable=True),
    sa.Column('free_ticket_min', sa.Integer(), nullable=True),
    sa.Column('free_tickets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('purchaser_email', sa.String(length=120), nullable=False),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('qr_code_filename', sa.String(length=255), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
